### ISSUE TITLE
Clock does not work

### ISSUE THREAD

**Issue by SimBu01** [leinich/ha-wordclock-esphome#3]
Hello,

I bought a "MirrorClock" kit some time ago.
This clock is controlled by remote control (color, brightness, etc.)
The time is fetched via WiFi.

Now I have seen this post.
Since my clock and the one built here are quite similar, I wanted to reprogram my "MirrorClock".

I have adapted the layout of the letters.

However, nothing happens when I turn on the clock.
I can only control the LEDs as a complete strip like a normal LED strip.

Can you help me there?

Greetings
SimBu01

**Comment by leinich** [comment]
Please make sure, to select a not uses GPIO in the yaml and only specify the correct GPIO in wordclock.h
