### ISSUE TITLE
esp32 unresponsive 

### ISSUE THREAD

**Issue by bagges** [leinich/ha-wordclock-esphome#8]
After uploading the code to an esp32 dev kit v4 the esp gets unresponsive. Device shows up but it can only answer one of ten ping requests. Clock / OTA does not work. Do you have an idea what could be wrong?

**Comment by leinich** [comment]
Sorry no Idea.
I'm using an esp8266 at a very bad location regarding WIFI quality.
I have some high ping values like 95ms but no package losts. Once I place it near to the WIFI Access Point the values are good and around 9 to 14ms.
Does the logs give any hints? Maybe voltage issues?

**Comment by bagges** [comment]
Today I tried some stuff. I changed to a polling component and the problem is gone. I have now some other problems that I have to figure.
